version: "3"
services:
  besu:
    image: "tmio/besu-keccak:latest"
    container_name: "besu"
    ports:
      - 8545:8545
      - 30303:30303
      - 30303:30303/udp
    volumes:
     - ./data:/var/data
     - ./genesis.json:/var/genesis.json
    command: --data-path=/var/data --Xethstats=besu:astorsecret@ethstats:3000 --rpc-http-enabled --rpc-http-api=admin,eth,debug,miner,net,txpool,priv,trace,web3 --rpc-http-cors-origins="all" --genesis-file=/var/genesis.json --host-allowlist=* --miner-enabled --miner-coinbase=fe3b557e8fb62b89f4916b721be55ceb828dbd73 --miner-stratum-enabled
    restart: unless-stopped
    depends_on: 
      - ethstats
  miner:
    image: "tmio/keccak-cpu-miner:latest"
    container_name: "miner"
    command: http://besu:8545 -n 1000
    depends_on:
      - besu
    restart: always
  ethstats:
    image: "puppeth/ethstats"
    container_name: ethstats
    ports:
      - 80:3000
    environment:
      - WS_SECRET=astorsecret